// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Veri.Kaynak;

namespace Veri.Migrations
{
    [DbContext(typeof(YpmSebil))]
    [Migration("20180313115626_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GercekVarlik.Mulk.Varlik.Kisi.Ortak.Kisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.Property<string>("EPosta");

                    b.Property<string>("Sifre");

                    b.Property<string>("Soyad");

                    b.HasKey("Id");

                    b.ToTable("KisiTbl");
                });
#pragma warning restore 612, 618
        }
    }
}
